<!-- Generated from canonical reference -->
<!-- Component: CMP-accordion -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-accordion">
    <div class="ael-accordion__item">
      <button class="ael-accordion__trigger">
        <div>
          Section One
        </div>
        <svg class="ael-accordion__icon">
          <div></div>
        </svg>
      </button>
      <div class="ael-accordion__content" role="region">
        <div>
          Content for section one.
        </div>
      </div>
    </div>
    <div class="ael-accordion__item">
      <button class="ael-accordion__trigger">
        <div>
          Section Two
        </div>
        <svg class="ael-accordion__icon">
          <div></div>
        </svg>
      </button>
      <div class="ael-accordion__content" role="region">
        <div>
          Content for section two.
        </div>
      </div>
    </div>
  </div>
</template>
