<!-- Generated from canonical reference -->
<!-- Component: CMP-button -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <button class="ael-button ael-button--primary ael-button--md">
    Button Label
  </button>
</template>
