<!-- Generated from canonical reference -->
<!-- Component: CMP-drawer -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>
import { ref, onMounted } from 'vue';

const props = defineProps({
  open: { type: Boolean, default: false },
});

const emit = defineEmits(['close']);

const dialogRef = ref(null);

onMounted(() => {
  if (!props.open) return;
  const el = dialogRef.value;
  if (!el) return;
  const focusable = el.querySelectorAll(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
  );
  focusable?.[0]?.focus();
});

</script>

<template>
  <div class="ael-drawer ael-drawer--right">
    <div class="ael-drawer__backdrop"></div>
    <div class="ael-drawer__panel" role="dialog">
      <div>
        Drawer Title
      </div>
      <div>
        Drawer content goes here.
      </div>
    </div>
  </div>
</template>
