<!-- Generated from canonical reference -->
<!-- Component: CMP-text-input -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-input">
    <label class="ael-input__label">
      Label
    </label>
    <div class="ael-input__wrapper">
      <input class="ael-input__field" />
      <span class="ael-input__helper">
        Helper text
      </span>
    </div>
  </div>
</template>
