<!-- Generated from canonical reference -->
<!-- Component: CMP-menu -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-menu" role="menu">
    <span class="ael-menu__label">
      Actions
    </span>
    <button class="ael-menu__item" role="menuitem">
      <svg class="ael-menu__icon">
        <div></div>
      </svg>
      Edit
    </button>
    <button class="ael-menu__item" role="menuitem">
      <svg class="ael-menu__icon">
        <div></div>
      </svg>
      Duplicate
    </button>
    <hr class="ael-menu__divider" role="separator" />
    <button class="ael-menu__item" role="menuitem">
      Delete
    </button>
  </div>
</template>
