<!-- Generated from canonical reference -->
<!-- Component: CMP-modal -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>
import { ref, onMounted } from 'vue';

const props = defineProps({
  open: { type: Boolean, default: false },
});

const emit = defineEmits(['close']);

const dialogRef = ref(null);

onMounted(() => {
  if (!props.open) return;
  const el = dialogRef.value;
  if (!el) return;
  const focusable = el.querySelectorAll(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
  );
  focusable?.[0]?.focus();
});

</script>

<template>
  <div class="ael-modal">
    <div class="ael-modal__backdrop">
      <div class="ael-modal__dialog" role="dialog">
        <div class="ael-modal__header">
          {{ header }}
          <button class="ael-modal__close" @click="$emit('close')">
            ×
          </button>
        </div>
        <div class="ael-modal__body">
          {{ body }}
        </div>
        <div class="ael-modal__footer">
          {{ footer }}
        </div>
      </div>
    </div>
  </div>
</template>
