<!-- Generated from canonical reference -->
<!-- Component: CMP-select -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-select">
    <label class="ael-select__label">
      Label
    </label>
    <div class="ael-select__wrapper">
      <select class="ael-select__field">
        <div>
          Select an option
        </div>
        <div>
          Option One
        </div>
        <div>
          Option Two
        </div>
      </select>
      <svg class="ael-select__chevron">
        <div></div>
      </svg>
    </div>
    <span class="ael-select__helper">
      Helper text
    </span>
  </div>
</template>
