<!-- Generated from canonical reference -->
<!-- Component: CMP-stepper -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-stepper">
    <div class="ael-stepper__step ael-stepper__step--completed">
      <svg class="ael-stepper__indicator">
        1
      </svg>
      <label class="ael-stepper__label">
        {{ step1Label }}
      </label>
      <div class="ael-stepper__connector"></div>
    </div>
    <div class="ael-stepper__step ael-stepper__step--active">
      <svg class="ael-stepper__indicator">
        2
      </svg>
      <label class="ael-stepper__label">
        {{ step2Label }}
      </label>
      <div class="ael-stepper__connector"></div>
    </div>
    <div class="ael-stepper__step">
      <svg class="ael-stepper__indicator">
        3
      </svg>
      <label class="ael-stepper__label">
        {{ step3Label }}
      </label>
    </div>
  </div>
</template>
