<!-- Generated from canonical reference -->
<!-- Component: CMP-tabs -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-tabs" role="tablist">
    <button class="ael-tabs__tab ael-tabs__tab--active" role="tab">
      Tab One
    </button>
    <button class="ael-tabs__tab" role="tab">
      Tab Two
    </button>
    <button class="ael-tabs__tab" role="tab">
      Tab Three
    </button>
  </div>
</template>
