<!-- Generated from canonical reference -->
<!-- Component: CMP-textarea -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-textarea">
    <label class="ael-textarea__label">
      Label
    </label>
    <input class="ael-textarea__field" />
    <span class="ael-textarea__helper">
      Helper text
    </span>
  </div>
</template>
