<!-- Generated from canonical reference -->
<!-- Component: CMP-timeline -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-timeline">
    <div class="ael-timeline__item ael-timeline__item--active">
      <svg class="ael-timeline__dot"></svg>
      <div class="ael-timeline__content">
        <div class="ael-timeline__time">
          {{ time }}
        </div>
        {{ title }}
        {{ description }}
      </div>
    </div>
  </div>
</template>
