<!-- Generated from canonical reference -->
<!-- Component: CMP-toast -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-toast" role="status">
    <div>
      Operation completed successfully.
    </div>
  </div>
</template>
