<!-- Generated from canonical reference -->
<!-- Component: CMP-tooltip -->
<!-- Auto-generated by AEL Compiler (Vue Renderer) — DO NOT EDIT -->
<!-- Source: AEL Compiler IR v1.0 -->

<script setup>

</script>

<template>
  <div class="ael-tooltip" role="tooltip">
    This is a helpful tooltip.
  </div>
</template>
