//
// AEL Design System — Swift Token Constants
// Generated by 09-Build/generators/swift-generator.js
// Source: 06-Implementation/tokens/
// DO NOT EDIT — regenerate via: node 09-Build/build.js
//

import SwiftUI

public enum AELTokens {
    public enum Blur {
        /// Large blur — prominent backdrop, modal backgrounds
        public static let lg: CGFloat = 16
        /// Medium blur — glass-morphism cards, overlays
        public static let md: CGFloat = 8
        /// Small blur — subtle backdrop effects
        public static let sm: CGFloat = 4
        /// Extra large blur — full-screen overlay effects
        public static let xl: CGFloat = 24
    }

    public enum Border {
        /// Large border — prominent emphasis, decorative
        public static let widthLg: CGFloat = 4
        /// Medium border — focus rings, active states, emphasis
        public static let widthMd: CGFloat = 2
        /// No border — default state, border-less components
        public static let widthNone: CGFloat = 0
        /// Small border — dividers, light outlines, inputs
        public static let widthSm: CGFloat = 1
    }

    public enum Breakpoint {
        /// Desktop breakpoint — 1440px and above
        public static let desktop: CGFloat = 1440
        /// Laptop breakpoint — 1024px and above
        public static let laptop: CGFloat = 1024
        /// Tablet breakpoint — 768px and above
        public static let tablet: CGFloat = 768
    }

    public enum Color {
        /// Brand accent amber — identity.html tag-amber
        public static let accentAmber: SwiftUI.Color = SwiftUI.Color(hex: "#F59E0B")
        /// Brand accent pink — identity.html tag-pink
        public static let accentPink: SwiftUI.Color = SwiftUI.Color(hex: "#FF4D8D")
        /// Brand accent teal — identity.html tag-teal
        public static let accentTeal: SwiftUI.Color = SwiftUI.Color(hex: "#00D4AA")
        /// Brand accent violet — identity.html tag-violet
        public static let accentViolet: SwiftUI.Color = SwiftUI.Color(hex: "#6C47FF")
        /// Page backgrounds
        public static let background: SwiftUI.Color = SwiftUI.Color(hex: "#FFFFFF")
        /// Secondary background, section surfaces — neutral-100 per identity.html
        public static let backgroundSecondary: SwiftUI.Color = SwiftUI.Color(hex: "#F5F5F5")
        /// Primary text, high-contrast elements
        public static let black: SwiftUI.Color = SwiftUI.Color(hex: "#000000")
        /// Dividers, outlines, default borders — neutral-200 per identity.html
        public static let border: SwiftUI.Color = SwiftUI.Color(hex: "#E5E5E5")
        /// Focus ring, active border
        public static let borderFocus: SwiftUI.Color = SwiftUI.Color(hex: "#0074FF")
        /// Brand Primary — Logo, headlines, accents, brand identity
        public static let brandPrimary: SwiftUI.Color = SwiftUI.Color(hex: "#0074FF")
        /// Errors, destructive actions — per identity.html
        public static let error: SwiftUI.Color = SwiftUI.Color(hex: "#EF4444")
        /// Section backgrounds, hover states — neutral-100 per identity.html
        public static let gray100: SwiftUI.Color = SwiftUI.Color(hex: "#F5F5F5")
        /// Borders, dividers, disabled states — neutral-200 per identity.html
        public static let gray200: SwiftUI.Color = SwiftUI.Color(hex: "#E5E5E5")
        /// Placeholder backgrounds, subtle separators — neutral-300 per identity.html
        public static let gray300: SwiftUI.Color = SwiftUI.Color(hex: "#D4D4D4")
        /// Placeholder text, secondary icons — neutral-400 per identity.html
        public static let gray400: SwiftUI.Color = SwiftUI.Color(hex: "#A3A3A3")
        /// Subtle background, card surfaces — neutral-50 per identity.html
        public static let gray50: SwiftUI.Color = SwiftUI.Color(hex: "#FAFAFA")
        /// Disabled text, inactive controls — neutral-500 per identity.html
        public static let gray500: SwiftUI.Color = SwiftUI.Color(hex: "#737373")
        /// Secondary text, captions — neutral-600 per identity.html
        public static let gray600: SwiftUI.Color = SwiftUI.Color(hex: "#525252")
        /// Medium-emphasis body text — neutral-700 per identity.html
        public static let gray700: SwiftUI.Color = SwiftUI.Color(hex: "#2D2D2D")
        /// Body text, high-emphasis content — neutral-800 per identity.html
        public static let gray800: SwiftUI.Color = SwiftUI.Color(hex: "#1A1A1A")
        /// Highest emphasis text, dark surfaces — neutral-900 per identity.html
        public static let gray900: SwiftUI.Color = SwiftUI.Color(hex: "#111111")
        /// Informational states, help text — per identity.html
        public static let info: SwiftUI.Color = SwiftUI.Color(hex: "#3B82F6")
        /// CTAs, links, active states
        public static let primary: SwiftUI.Color = SwiftUI.Color(hex: "#0074FF")
        /// Primary active/pressed state
        public static let primaryActive: SwiftUI.Color = SwiftUI.Color(hex: "#004099")
        /// Primary hover state — per identity.html .btn-primary:hover
        public static let primaryHover: SwiftUI.Color = SwiftUI.Color(hex: "#0062D6")
        /// Secondary actions, badges, tags — brand violet per identity.html
        public static let secondary: SwiftUI.Color = SwiftUI.Color(hex: "#6C47FF")
        /// Confirmations, positive states — per identity.html
        public static let success: SwiftUI.Color = SwiftUI.Color(hex: "#10B981")
        /// Card backgrounds, containers — neutral-50 per identity.html
        public static let surface: SwiftUI.Color = SwiftUI.Color(hex: "#FAFAFA")
        /// Elevated surface, modal backgrounds — neutral-100 per identity.html
        public static let surfaceSecondary: SwiftUI.Color = SwiftUI.Color(hex: "#F5F5F5")
        /// Disabled text on any background — neutral-400 per identity.html
        public static let textDisabled: SwiftUI.Color = SwiftUI.Color(hex: "#A3A3A3")
        /// Text on dark or primary backgrounds
        public static let textInverse: SwiftUI.Color = SwiftUI.Color(hex: "#FFFFFF")
        /// Primary text on light backgrounds — neutral-900 per identity.html
        public static let textPrimary: SwiftUI.Color = SwiftUI.Color(hex: "#111111")
        /// Secondary text, captions, descriptions — neutral-600 per identity.html
        public static let textSecondary: SwiftUI.Color = SwiftUI.Color(hex: "#525252")
        /// Alerts, cautionary states — brand amber per identity.html
        public static let warning: SwiftUI.Color = SwiftUI.Color(hex: "#F59E0B")
        /// Backgrounds, reverse text, negative space
        public static let white: SwiftUI.Color = SwiftUI.Color(hex: "#FFFFFF")
    }

    public enum Elevation {
        /// Modal — dialogs, drawers. Highest content elevation
        public static let modal: CGFloat = 3
        /// Overlay — dropdowns, sheets, backdrops
        public static let overlay: CGFloat = 2
        /// Raised — cards, elevated containers. Slight visual lift.
        public static let raised: CGFloat = 1
        /// Surface — flat, no elevation. Default background.
        public static let surface: CGFloat = 0
    }

    public enum Grid {
        /// Default grid column count
        public static let columns: CGFloat = 12
        /// Grid gutter on desktop
        public static let gutterDesktop: CGFloat = 32
        /// Grid gutter on mobile
        public static let gutterMobile: CGFloat = 16
        /// Grid gutter on tablet
        public static let gutterTablet: CGFloat = 24
        /// Page margin on desktop
        public static let marginDesktop: CGFloat = 64
        /// Page margin on mobile
        public static let marginMobile: CGFloat = 16
        /// Page margin on tablet
        public static let marginTablet: CGFloat = 32
        /// Maximum content width
        public static let maxWidth: CGFloat = 1280
    }

    public enum Icon {
        /// Large icon — featured, navigation
        public static let sizeLg: CGFloat = 32
        /// Medium icon — default, inline with body text
        public static let sizeMd: CGFloat = 24
        /// Small icon — compact UI, inline with small text
        public static let sizeSm: CGFloat = 16
        /// Extra large icon — hero, empty states
        public static let sizeXl: CGFloat = 48
        /// Large stroke width — bold icons
        public static let strokeWidthLg: CGFloat = 2.5
        /// Medium stroke width — default
        public static let strokeWidthMd: CGFloat = 2
        /// Small stroke width — detailed icons
        public static let strokeWidthSm: CGFloat = 1.5
    }

    public enum Motion {
        /// Fast — hover transitions, micro-interactions, icon changes
        public static let durationFast: TimeInterval = 0.15
        /// Instant — no animation, immediate state change
        public static let durationInstant: TimeInterval = 0
        /// Normal — component transitions, expand/collapse, toggle
        public static let durationNormal: TimeInterval = 0.3
        /// Slow — page transitions, modal open/close, complex animations
        public static let durationSlow: TimeInterval = 0.5
        /// Default easing — general-purpose transitions
        public static let easingDefault: String = "cubic-bezier(0.4, 0, 0.2, 1)"
        /// Ease-in — elements entering the viewport, appearing
        public static let easingIn: String = "cubic-bezier(0.4, 0, 1, 1)"
        /// Ease-out — elements leaving the viewport, disappearing
        public static let easingOut: String = "cubic-bezier(0, 0, 0.2, 1)"
    }

    public enum Opacity {
        /// Disabled opacity — disabled buttons, inputs, controls
        public static let disabled: CGFloat = 0.4
        /// Focus overlay opacity — focus ring visibility
        public static let focus: CGFloat = 0.12
        /// Hover overlay opacity — hover state darkening
        public static let hover: CGFloat = 0.08
        /// Pressed overlay opacity — active/pressed state darkening
        public static let pressed: CGFloat = 0.16
    }

    public enum Radius {
        /// Fully rounded — pills, badges, avatars, circular buttons
        public static let full: CGFloat = 9999
        /// Large radius — modals, large cards, panels
        public static let lg: CGFloat = 12
        /// Medium radius — buttons, inputs, cards
        public static let md: CGFloat = 8
        /// No border radius — sharp corners
        public static let none: CGFloat = 0
        /// Small radius — checkboxes, tags, small inputs
        public static let sm: CGFloat = 4
        /// Extra large radius — containers, image cards
        public static let xl: CGFloat = 16
    }

    public enum Shadow {
        /// Large shadow — modals, drawers, prominent elevation
        public static let lg: String = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)"
        /// Medium shadow — dropdowns, elevated cards, hover state
        public static let md: String = "0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -2px rgba(0, 0, 0, 0.05)"
        /// No shadow — flat surfaces, default state
        public static let none: String = "none"
        /// Small shadow — subtle elevation, cards on white
        public static let sm: String = "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
        /// Extra large shadow — highest elevation, hero sections
        public static let xl: String = "0 20px 25px -5px rgba(0, 0, 0, 0.10), 0 8px 10px -6px rgba(0, 0, 0, 0.05)"
    }

    public enum Size {
        /// Large avatar
        public static let avatarLg: CGFloat = 48
        /// Medium avatar — default
        public static let avatarMd: CGFloat = 40
        /// Small avatar
        public static let avatarSm: CGFloat = 32
        /// Extra large avatar
        public static let avatarXl: CGFloat = 64
        /// Extra small avatar
        public static let avatarXs: CGFloat = 24
        /// Large button height
        public static let buttonLg: CGFloat = 52
        /// Medium button height — default
        public static let buttonMd: CGFloat = 44
        /// Small button height
        public static let buttonSm: CGFloat = 36
        /// Extra large button height
        public static let buttonXl: CGFloat = 60
        /// Extra small button height
        public static let buttonXs: CGFloat = 28
        /// Large icon container
        public static let iconContainerLg: CGFloat = 48
        /// Medium icon container — default
        public static let iconContainerMd: CGFloat = 40
        /// Small icon container
        public static let iconContainerSm: CGFloat = 32
        /// Large logo height
        public static let logoHeightLg: CGFloat = 48
        /// Medium logo height — default
        public static let logoHeightMd: CGFloat = 32
        /// Small logo height
        public static let logoHeightSm: CGFloat = 24
    }

    public enum Spacing {
        /// 2XL — page margins, large container padding
        public static let _2xl: CGFloat = 40
        /// 3XL — hero section padding, major layout blocks
        public static let _3xl: CGFloat = 48
        /// 4XL — page-level spacing
        public static let _4xl: CGFloat = 56
        /// 5XL — large section separation
        public static let _5xl: CGFloat = 64
        /// 6XL — major layout spacing
        public static let _6xl: CGFloat = 80
        /// 7XL — maximum layout spacing
        public static let _7xl: CGFloat = 96
        /// 8XL — ultra large separation
        public static let _8xl: CGFloat = 128
        /// Large — section padding, component separation
        public static let lg: CGFloat = 24
        /// Medium — default component padding, card insets
        public static let md: CGFloat = 16
        /// Small — base unit, component inner padding, compact layouts
        public static let sm: CGFloat = 8
        /// Extra large — layout gaps, major section spacing
        public static let xl: CGFloat = 32
        /// Extra small — icon padding, tight inline spacing
        public static let xs: CGFloat = 4
    }

    public enum Typography {
        /// Monospace font for code, data, technical content
        public static let fontMono: String = "JetBrains Mono"
        /// Primary font for body text, headings, UI
        public static let fontPrimary: String = "Inter"
        /// Secondary font for headlines, display text
        public static let fontSecondary: String = "SF Pro Display"
        /// Normal letter spacing — body text, UI
        public static let letterspacingNormal: CGFloat = 0
        /// Tight letter spacing — headings, display text
        public static let letterspacingTight: CGFloat = -0.02
        /// Wide letter spacing — labels, captions, uppercase
        public static let letterspacingWide: CGFloat = 0.04
        /// Normal line height — body text, UI
        public static let lineheightNormal: CGFloat = 1.5
        /// Relaxed line height — long-form reading, articles
        public static let lineheightRelaxed: CGFloat = 1.8
        /// Tight line height — headings, display text
        public static let lineheightTight: CGFloat = 1.2
        /// Body text — paragraphs, form labels, lists
        public static let sizeBody: CGFloat = 16
        /// Caption text — image captions, footnotes, legal
        public static let sizeCaption: CGFloat = 12
        /// Display text — hero headings, landing pages
        public static let sizeDisplay: CGFloat = 64
        /// Heading 1 — page titles
        public static let sizeH1: CGFloat = 48
        /// Heading 2 — section titles
        public static let sizeH2: CGFloat = 40
        /// Heading 3 — subsection titles
        public static let sizeH3: CGFloat = 32
        /// Heading 4 — card titles, panel headers
        public static let sizeH4: CGFloat = 24
        /// Heading 5 — minor headings
        public static let sizeH5: CGFloat = 20
        /// Heading 6 — smallest heading
        public static let sizeH6: CGFloat = 18
        /// Small text — secondary information, metadata
        public static let sizeSmall: CGFloat = 14
        /// Bold weight — primary headings, emphasis
        public static let weightBold: CGFloat = 700
        /// Light weight — display text, large headings
        public static let weightLight: CGFloat = 300
        /// Medium weight — emphasized text, subheadings
        public static let weightMedium: CGFloat = 500
        /// Regular weight — body text, UI labels
        public static let weightRegular: CGFloat = 400
        /// Semibold weight — section headings, CTAs
        public static let weightSemibold: CGFloat = 600
    }

    public enum Zindex {
        /// Base content — default stacking context
        public static let base: CGFloat = 0
        /// Side drawers, slide-out panels
        public static let drawer: CGFloat = 400
        /// Dropdown menus, select options
        public static let dropdown: CGFloat = 100
        /// Modal dialogs, alert dialogs
        public static let modal: CGFloat = 500
        /// Overlays, backdrops
        public static let overlay: CGFloat = 300
        /// Sticky headers, fixed navigation
        public static let sticky: CGFloat = 200
        /// Toast notifications, snackbars
        public static let toast: CGFloat = 700
        /// Tooltips, popovers
        public static let tooltip: CGFloat = 600
    }

}
