// Generated from canonical reference
// Component: CMP-accordion
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Accordion({ ...props }) {
  return (
    <div className="ael-accordion">
      <div className="ael-accordion__item">
        <button className="ael-accordion__trigger" aria-expanded="false">
          <div>
            "Section One"
          </div>
{open && (
            <svg className="ael-accordion__icon" aria-hidden="true">
            <div></div>
          </svg>
          )}
        </button>
        <div className="ael-accordion__content" role="region">
          <div>
            "Content for section one."
          </div>
        </div>
      </div>
      <div className="ael-accordion__item">
        <button className="ael-accordion__trigger" aria-expanded="false">
          <div>
            "Section Two"
          </div>
{open && (
            <svg className="ael-accordion__icon" aria-hidden="true">
            <div></div>
          </svg>
          )}
        </button>
        <div className="ael-accordion__content" role="region">
          <div>
            "Content for section two."
          </div>
        </div>
      </div>
    </div>
  );
}
