// Generated from canonical reference
// Component: CMP-button
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Button({ ...props }) {
  return (
    <button className="ael-button ael-button--primary ael-button--md">
      "Button Label"
    </button>
  );
}
