// Generated from canonical reference
// Component: CMP-drawer
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React, { useEffect, useRef, useCallback } from 'react';

export function Drawer({ open, onClose }) {
  const dialogRef = useRef(null);

  useEffect(() => {
    if (!open) return;
    const el = dialogRef.current;
    if (!el) return;
    const focusable = el.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    focusable?.[0]?.focus();
    const handler = (e) => { if (e.key === 'Escape') onClose?.(); };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [open, onClose]);

  return (
{open && (
      <div className="ael-drawer ael-drawer--right">
      <div className="ael-drawer__backdrop"></div>
      <div className="ael-drawer__panel" role="dialog" aria-modal="true">
        <div>
          "Drawer Title"
        </div>
        <div>
          "Drawer content goes here."
        </div>
      </div>
    </div>
    )}
  );
}
