// Generated from canonical reference
// Component: CMP-text-input
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Text Input({ ...props }) {
  return (
    <div className="ael-input">
      <label className="ael-input__label">
        "Label"
      </label>
      <div className="ael-input__wrapper">
        <input className="ael-input__field" />
        <span className="ael-input__helper">
          "Helper text"
        </span>
      </div>
    </div>
  );
}
