// Generated from canonical reference
// Component: CMP-menu
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Menu({ ...props }) {
  return (
{open && (
      <div className="ael-menu" role="menu">
      <span className="ael-menu__label">
        "Actions"
      </span>
      <button className="ael-menu__item" role="menuitem">
{open && (
          <svg className="ael-menu__icon" aria-hidden="true">
          <div></div>
        </svg>
        )}
        "Edit"
      </button>
      <button className="ael-menu__item" role="menuitem">
{open && (
          <svg className="ael-menu__icon" aria-hidden="true">
          <div></div>
        </svg>
        )}
        "Duplicate"
      </button>
      <hr className="ael-menu__divider" role="separator"></hr>
      <button className="ael-menu__item" role="menuitem">
        "Delete"
      </button>
    </div>
    )}
  );
}
