// Generated from canonical reference
// Component: CMP-modal
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React, { useEffect, useRef, useCallback } from 'react';

export function Modal({ open, onClose, header, body, footer }) {
  const dialogRef = useRef(null);

  useEffect(() => {
    if (!open) return;
    const el = dialogRef.current;
    if (!el) return;
    const focusable = el.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    focusable?.[0]?.focus();
    const handler = (e) => { if (e.key === 'Escape') onClose?.(); };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [open, onClose]);

  return (
{open && (
      <div className="ael-modal">
      <div className="ael-modal__backdrop">
        <div className="ael-modal__dialog" role="dialog" aria-modal="true" aria-labelledby="modal-title">
          <div className="ael-modal__header">
            {header}
            <button className="ael-modal__close" aria-label="Close" onClick={onClose}>
              "\u00d7"
            </button>
          </div>
          <div className="ael-modal__body">
            {body}
          </div>
          <div className="ael-modal__footer">
            {footer}
          </div>
        </div>
      </div>
    </div>
    )}
  );
}
