// Generated from canonical reference
// Component: CMP-select
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Select({ ...props }) {
  return (
    <div className="ael-select">
      <label className="ael-select__label">
        "Label"
      </label>
      <div className="ael-select__wrapper">
        <select className="ael-select__field">
          <div>
            "Select an option"
          </div>
          <div>
            "Option One"
          </div>
          <div>
            "Option Two"
          </div>
        </select>
{open && (
          <svg className="ael-select__chevron" aria-hidden="true">
          <div></div>
        </svg>
        )}
      </div>
      <span className="ael-select__helper">
        "Helper text"
      </span>
    </div>
  );
}
