// Generated from canonical reference
// Component: CMP-stepper
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Stepper({ step1Label, step2Label, step3Label }) {
  return (
    <div className="ael-stepper">
      <div className="ael-stepper__step ael-stepper__step--completed">
        <svg className="ael-stepper__indicator">
          "1"
        </svg>
        <label className="ael-stepper__label">
          {step1Label}
        </label>
        <div className="ael-stepper__connector"></div>
      </div>
      <div className="ael-stepper__step ael-stepper__step--active">
        <svg className="ael-stepper__indicator">
          "2"
        </svg>
        <label className="ael-stepper__label">
          {step2Label}
        </label>
        <div className="ael-stepper__connector"></div>
      </div>
      <div className="ael-stepper__step">
        <svg className="ael-stepper__indicator">
          "3"
        </svg>
        <label className="ael-stepper__label">
          {step3Label}
        </label>
      </div>
    </div>
  );
}
