// Generated from canonical reference
// Component: CMP-tabs
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Tabs({ ...props }) {
  return (
    <div className="ael-tabs" role="tablist">
      <button className="ael-tabs__tab ael-tabs__tab--active" role="tab" aria-selected="true">
        "Tab One"
      </button>
      <button className="ael-tabs__tab" role="tab" aria-selected="false">
        "Tab Two"
      </button>
      <button className="ael-tabs__tab" role="tab" aria-selected="false">
        "Tab Three"
      </button>
    </div>
  );
}
