// Generated from canonical reference
// Component: CMP-textarea
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Textarea({ ...props }) {
  return (
    <div className="ael-textarea">
      <label className="ael-textarea__label">
        "Label"
      </label>
      <input className="ael-textarea__field" />
      <span className="ael-textarea__helper">
        "Helper text"
      </span>
    </div>
  );
}
