// Generated from canonical reference
// Component: CMP-timeline
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Timeline({ time, title, description }) {
  return (
    <div className="ael-timeline">
      <div className="ael-timeline__item ael-timeline__item--active">
        <svg className="ael-timeline__dot"></svg>
        <div className="ael-timeline__content">
          <div className="ael-timeline__time">
            {time}
          </div>
          {title}
          {description}
        </div>
      </div>
    </div>
  );
}
