// Generated from canonical reference
// Component: CMP-tooltip
// Auto-generated by AEL Compiler (React Renderer) — DO NOT EDIT
// Source: AEL Compiler IR v1.0

import React from 'react';

export function Tooltip({ ...props }) {
  return (
{open && (
      <div className="ael-tooltip" role="tooltip">
      "This is a helpful tooltip."
    </div>
    )}
  );
}
